version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: prova
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     restart: always
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: ''
     ports:
       - "8090:80"
     depends_on:
       - db

  node:
    build: 
       context: .
       dockerfile: DockerFile

    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  

  

volumes:
  db-data: 